### ISSUE TITLE
不考虑基于OpenTracing API的csharp版吗？

### ISSUE THREAD

**Issue by fs7744** [dotnet-lab/Butterfly#1]
OpenTracing API定义了很多语言版本的api模板
比如 csharp的 ：
https://github.com/opentracing/opentracing-csharp 
不考虑基于它吗？

**Comment by liuhaoyang** [comment]
@fs7744 研究过opentracing-csharp，但是感觉opentracing-csharp定义的api不够精细，所以在自己实现更方便易用的api。目前的openTracing api 也是在参考opentracing-csharp

**Comment by fs7744** [comment]
所噶
